### ISSUE TITLE
اشکال در صفحه لیست کاربران

### ISSUE THREAD

**Issue by milanifard** [milanifard/SadafSocialNetwork#5]
زمانیکه روی دکمه ذیل ستون دنبال کردن کلیک می شود، پس از نمایش یک مودال بلافاصله به صفحه پروفایل فرد مربوطه می رود و امکان انتخاب گزینه را به کاربر نمی دهد

**Comment by Galiold** [comment]
لطفا تغییرات ایجاد شده را بررسی نمایید @milanifard
